---
title: "Example"
subtitle: "SUBTITLE"
author: "AUTHORS"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: inline
---

# $\LaTeX$ Math

This is just markdown that can include latex math.

$$
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}
$$

# System Info

```{python}
import IPython
print(IPython.sys_info())
```

# Data

```{python}
import pandas as pd
import numpy as np
curve = pd.DataFrame(np.arange(0.0, 2.0, 0.01), columns=list('t'))
curve['x'] = 1 + np.sin(2 * np.pi * curve['t'])
```

```{r}
# access python variable via reticulate - requires RStudio 1.2+ to work interactively
library(reticulate)
py$curve
```

# Plot

```{r, fig.width=8, fig.height=4}
# python plots (e.g. matplotlib) require RStudio 1.2+ for proper rendering
# using reticulate and ggplot instead (will work only in knitted document)
library(ggplot2)
ggplot(py$curve) +
  aes(x = t, y = x) + 
  geom_line() + 
  theme_bw()
```